CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title TEXT,
  description TEXT NOT NULL DEFAULT '',
  annual_income_min INTEGER,
  annual_income_max INTEGER,
  annual_income_raw TEXT,
  required_skills TEXT[] NOT NULL DEFAULT '{}',
  preferred_skills TEXT[] NOT NULL DEFAULT '{}',
  appeal_points TEXT,
  reference_info TEXT,
  required_language TEXT,
  required_certifications TEXT,
  preferred_language TEXT,
  preferred_certifications TEXT,
  location TEXT,
  notes TEXT,
  input_method TEXT NOT NULL DEFAULT 'crawl',
  source_url TEXT NOT NULL UNIQUE,
  crawled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  normalized_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS job_skills (
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  skill_type TEXT NOT NULL CHECK (skill_type IN ('required', 'preferred')),
  PRIMARY KEY (job_id, skill_id, skill_type)
);

CREATE TABLE IF NOT EXISTS dictionary_terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dictionary_type TEXT NOT NULL CHECK (dictionary_type IN ('skill', 'certification')),
  term TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (dictionary_type, term)
);

CREATE TABLE IF NOT EXISTS company_parser_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL UNIQUE,
  parser_config JSONB NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_jobs_company_id ON jobs(company_id);
CREATE INDEX IF NOT EXISTS idx_jobs_crawled_at ON jobs(crawled_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_required_skills ON jobs USING GIN (required_skills);
CREATE INDEX IF NOT EXISTS idx_jobs_preferred_skills ON jobs USING GIN (preferred_skills);
CREATE INDEX IF NOT EXISTS idx_job_skills_skill_type ON job_skills(skill_type);
CREATE INDEX IF NOT EXISTS idx_dictionary_terms_type_order
ON dictionary_terms(dictionary_type, sort_order, term);
CREATE INDEX IF NOT EXISTS idx_company_parser_configs_enabled
ON company_parser_configs(enabled, company_name);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS companies_set_updated_at ON companies;
CREATE TRIGGER companies_set_updated_at
BEFORE UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS jobs_set_updated_at ON jobs;
CREATE TRIGGER jobs_set_updated_at
BEFORE UPDATE ON jobs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS dictionary_terms_set_updated_at ON dictionary_terms;
CREATE TRIGGER dictionary_terms_set_updated_at
BEFORE UPDATE ON dictionary_terms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS company_parser_configs_set_updated_at ON company_parser_configs;
CREATE TRIGGER company_parser_configs_set_updated_at
BEFORE UPDATE ON company_parser_configs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO company_parser_configs (company_name, parser_config, enabled)
VALUES (
  'NTT DATA',
  '{
    "titlePattern": "^【.+?】",
    "headings": {
      "company": ["募集元"],
      "description": ["職務内容"],
      "appealPoints": ["アピールポイント"],
      "referenceInfo": ["参考情報"],
      "requiredSkills": ["【必要条件】求める経験・スキル・知識", "必要条件】求める経験・スキル・知識"],
      "requiredLanguage": ["【必要条件】他言語力", "必要条件】他言語力"],
      "requiredCertifications": ["【必要条件】資格", "必要条件】資格"],
      "preferredSkills": ["【歓迎条件】求める経験・スキル・知識", "歓迎条件】求める経験・スキル・知識"],
      "preferredLanguage": ["【歓迎条件】他言語力", "歓迎条件】他言語力"],
      "preferredCertifications": ["【歓迎条件】資格", "歓迎条件】資格"],
      "income": ["待遇"],
      "location": ["勤務地"]
    },
    "sectionHeadings": [
      "募集元", "職務内容", "アピールポイント", "参考情報",
      "【必要条件】求める経験・スキル・知識", "【必要条件】他言語力", "【必要条件】資格",
      "【歓迎条件】求める経験・スキル・知識", "【歓迎条件】他言語力", "【歓迎条件】資格",
      "雇用形態", "想定役職", "労働形態", "待遇", "勤務地"
    ],
    "ignoreSkillPatterns": [
      "特になし", "必須", "歓迎", "条件", "以上", "以下", "勤務地", "勤務", "資格", "語学", "英語力"
    ]
  }'::jsonb,
  TRUE
)
ON CONFLICT (company_name) DO UPDATE
SET parser_config = EXCLUDED.parser_config,
    enabled = EXCLUDED.enabled;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON companies TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON jobs TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON skills TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON job_skills TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON dictionary_terms TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON company_parser_configs TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE dictionary_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_parser_configs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow anon read companies" ON companies;
DROP POLICY IF EXISTS "allow anon write companies" ON companies;
DROP POLICY IF EXISTS "allow anon update companies" ON companies;
DROP POLICY IF EXISTS "allow anon read jobs" ON jobs;
DROP POLICY IF EXISTS "allow anon write jobs" ON jobs;
DROP POLICY IF EXISTS "allow anon update jobs" ON jobs;
DROP POLICY IF EXISTS "allow anon read skills" ON skills;
DROP POLICY IF EXISTS "allow anon write skills" ON skills;
DROP POLICY IF EXISTS "allow anon update skills" ON skills;
DROP POLICY IF EXISTS "allow anon read job_skills" ON job_skills;
DROP POLICY IF EXISTS "allow anon write job_skills" ON job_skills;
DROP POLICY IF EXISTS "allow anon update job_skills" ON job_skills;
DROP POLICY IF EXISTS "allow anon read dictionary_terms" ON dictionary_terms;
DROP POLICY IF EXISTS "allow anon write dictionary_terms" ON dictionary_terms;
DROP POLICY IF EXISTS "allow anon update dictionary_terms" ON dictionary_terms;
DROP POLICY IF EXISTS "allow anon delete dictionary_terms" ON dictionary_terms;
DROP POLICY IF EXISTS "allow anon read company_parser_configs" ON company_parser_configs;
DROP POLICY IF EXISTS "allow anon write company_parser_configs" ON company_parser_configs;
DROP POLICY IF EXISTS "allow anon update company_parser_configs" ON company_parser_configs;
DROP POLICY IF EXISTS "allow anon delete company_parser_configs" ON company_parser_configs;

CREATE POLICY "allow anon read companies"
ON companies FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write companies"
ON companies FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update companies"
ON companies FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon read jobs"
ON jobs FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write jobs"
ON jobs FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update jobs"
ON jobs FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon read skills"
ON skills FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write skills"
ON skills FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update skills"
ON skills FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon read job_skills"
ON job_skills FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write job_skills"
ON job_skills FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update job_skills"
ON job_skills FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon read dictionary_terms"
ON dictionary_terms FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write dictionary_terms"
ON dictionary_terms FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update dictionary_terms"
ON dictionary_terms FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon delete dictionary_terms"
ON dictionary_terms FOR DELETE TO anon, authenticated
USING (true);

CREATE POLICY "allow anon read company_parser_configs"
ON company_parser_configs FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "allow anon write company_parser_configs"
ON company_parser_configs FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "allow anon update company_parser_configs"
ON company_parser_configs FOR UPDATE TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "allow anon delete company_parser_configs"
ON company_parser_configs FOR DELETE TO anon, authenticated
USING (true);
